### PR TITLE
Updated xdg-open to latest rc to fix browser opening 3 tabs on Debian

### PR DESCRIPTION
**Pull request by CodisRedding**
The original repo by pwnall had a bug that had a manual resolution of replacing the xdg-open script from an external source. It seems that the code was never updated in his repo though.  I grabbed the rc1 code and updated the xdg-open script myself and found that is fixed the debian bug. 

First reference to the bug: https://github.com/pwnall/node-open/issues/7

Second reference to the bug: https://github.com/yeoman/generator-angular/issues/618#issuecomment-38031723

### CODE REVIEW

**Comment by josx** [comment]
+1, Please Merge, i am having the same issue!!

**Comment by ahoutkooper** [comment]
+1, Having the same issue over here.

**Comment by olivierrr** [comment]
+1

**Comment by lollipopman** [comment]
I have the same problem as well on Debian, I think it would be better to stop vendoring `xdg-open` and just rely on the user to have an installed copy, if they do not have the program installed print an error message.

**Comment by jjrdn** [comment]
https://github.com/sindresorhus/opn

**Pull request closed without merging**
